# -*- coding: utf-8 -*-
"""1단계.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDzrKu0ZSDMp_cr8bDVhzGDCZD4rqyUt

1번
"""

print('Hello World!')

"""2번"""

print('강한친구 대한육군')
print('강한친구 대한육군')

"""5번"""

A, B = input( ).split( )
print(int(A) + int(B))

"""6번"""

A, B = input( ).split( )
print(int(A) - int(B))

"""7번"""

A, B = input( ).split( )
print(int(A) * int(B))

"""8번"""

A, B = (input( ).split( ))
print(int(A) / int(B))

"""9번"""

A, B = input( ).split( )
print(int(A) + int(B))
print(int(A) - int(B))
print(int(A) * int(B))
print(int(A) / int(B))
print(int(A) % int(B))

"""10번"""

A, B, C = map(int, input( ).split( )) #map 리스트의 요소를 지정된 함수로 처리해주는 함수

print((A+B)%C)
print((A%C)+(B%C)%C)
print((A*B)%C)
print((A%C)*(B%C)%C)

"""11번"""

a = int(input())
b = int(input())

hund = int(b/100)
ten = int((b%100)/10)
one = int(b%10)

print(a*one)
print(a*ten)
print(a*hund)
print(a*b)