# -*- coding: utf-8 -*-
"""2단계.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zz3ua4ExOGFd3IQnLoNJ6GX4OKVhw5cG

1번
"""

A, B = map(int, input().split())

if A > B :
  print('>')
if A < B:
  print('<')
if A == B:
  print('=')

"""2번"""

score = int(input())

if (score <= 100) and (score >= 90):
  print('A')
elif (score < 90) and (score >= 80): 
  print('B')
elif (score <80) and (score >= 70):
  print('C')
elif (score <70) and (score >= 60):
  print('D')  
else:
  print('F')

"""3번"""

year = int(input())

if ((year%4==0) and (year%100!=0)) or ((year%4==0) and (year%400==0)):
  print(1)
else:
  print(0)

"""4번"""

x = int(input())
y = int(input())

if x > 0 and y > 0:
  print(1)
elif x < 0 and y > 0:
  print(2)
elif x < 0 and y < 0:
  print(3)
else:
  print(4)

"""5번"""

H, M = map(int, input().split())
if M < 45:
  if H == 0:
    H = 23
    M += 60
  else:
    H -= 1
    M += 60

print(H, M-45)