# -*- coding: utf-8 -*-
"""3단계.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WhxUA5gyYtna-F3xKdywPDc2RYgFVE5a

1번
"""

n = int(input())

for i in range(1,10):  # 1~9
    print(n, '*', i, '=', n*i)

"""2번"""

t = int(input())

for _ in range(t):
  a,b =map(int, input().split())
  print(a+b)

"""3번"""

n = int(input())

total = 0  # 변수에 0을 지정
for i in range(1, n+1) :  # 1부터 n까지
    total += i  # total = total + i와 같은 의미
print(total)

"""4번"""

import sys  # sys모듈 읽어들이기

t = int(sys.stdin.readline())

for _ in range(t):
    a,b = map(int, sys.stdin.readline().split())
    print(a+b)

"""5번"""

n = int(input())

for i in range(1, n+1):  # 1부터 n까지
    print(i)

"""6번"""

n = int(input())
for i in range(n, 0, -1):  # n부터 1까지 역순
    print(i)

"""7번"""

t = int(input())

for i in range(1, t+1):  # 1부터 t까지
    a, b = map(int, input().split())
    print(f'Case #{i}: {a+b}')

"""8번"""

t = int(input())

for x in range(1, t+1):  # 1부터 t까지
    a, b = map(int, input().split())
    print(f'Case #{x}: {a} + {b} = {a+b}')

"""9번"""

n = int(input())

for i in range(1, n+1):  # 1부터 n까지
    print('*' * i)

"""10번"""

a=int(input())
for i in range(1,a+1):
    print(" "*(a-i) + "*"*i)

"""11번"""

N, X = map(int, input().split())
A = list(map(int, input().split()))
for i in range(N):
    if A[i] < X:
        print(A[i], end=" ")