# -*- coding: utf-8 -*-
"""4단계.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nm4SyB_ZYJZ1SM6nsWaMmwVg2xEmvguO

1번
"""

while True:
  a, b = map(int, input().split())
  if a == 0 and b == 0:
    break
  print(a+b)

"""2번"""

while True:
    try:
        A, B = map(int, input().split())
        print(A+B)
    except:
        break

"""3번"""

n = int(input())
num = n
count = 0

while True:
  a = num // 10
  b = num% 10
  c = (a+b) % 10
  num = (b * 10) + c

  count = count + 1
  if(num == n):
    break
print(count)